name: run_ablunit_tests

on:
  workflow_call

jobs:
  run_ablunit_tests:
    name: run_ablunit_tests samples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      ## Example 1: ABLUnit test run
      ## * the `abl` action will automatically call `setup` if no OpenEdge installation is detected
      - uses: kenherring/openedge-actions/ablunit@85a25f0e55183c32ac2d3cd377060a3b103ce74e
        with:
          license: ${{ secrets.PROGRESS_CFG }}
          working-directory: 'run_ablunit_tests'
          test-file-pattern: 'src/*.cls'
