name: run_ablunit_tests
# description:  Sample workflow demonstrating how to run ablunit tests with kenherring/openedge-actions/ablunit

on:
  workflow_call

jobs:
  run_ablunit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      ## Example 1: ABLUnit test run
      ## * the `abl` action will automatically call `setup` if no OpenEdge installation is detected
      - uses: kenherring/openedge-actions/ablunit@b811495ee9ac5e8f3857f33dc2c7461a87d6fcbc
        with:
          license: ${{ secrets.PROGRESS_CFG }}
          working-directory: 'run_ablunit_tests'
          test-file-pattern: 'src/*.cls'
