name: run_ablunit_tests
# description:  Sample workflow demonstrating how to run ablunit tests with kenherring/openedge-actions/ablunit

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run_aablunit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      ## Example 1: ABLUnit test run
      ## * the `abl` action will automatically call `setup` if no OpenEdge installation is detected
      - uses: kenherring/openedge-actions/ablunit@103af1ee5899d23818e735d004ab5e717ed235ba
        with:
          license: ${{ secrets.PROGRESS_CFG }}
          test-file-pattern: 'run_ablunit_tests/src/*.cls'
